### PR TITLE
fix: exit code is 1 when expectations are not fulfilled

### LINKED ISSUE #193: Exit code is always 0
Is it me or the exit code is always `0`, no matter success or failure of the expectations?

### Config / CLI options

```
{
  "flags": {
    "runs": 3,
    "expectations": true,
    "chromeFlags": "--headless --no-sandbox"
  },
  "expectations": {
    "firstMeaningfulPaint": {
      "warn": ">=1",
      "error": ">=1"
    },
    "firstContentfulPaint": {
      "warn": ">=3",
      "error": ">=6"
    },
    "firstCPUIdle": {
      "warn": ">=8",
      "error": ">=10"
    },
    "interactive": {
      "warn": ">=8",
      "error": ">=12"
    },
    "speedIndex": {
      "warn": ">=3",
      "error": ">=6"
    }
  }
}
```

### Steps to reproduce.

`yarn pwmetrics --config pwmetrics.config.json https://ddg.gg`

### Output

```
pwmetrics.config.json https://ddg.gg
Launching Chrome
  ✓ Success: Run 1 of 3 finished successfully.
Launching Chrome
  ✓ Success: Run 2 of 3 finished successfully.
Launching Chrome
  ✓ Success: Run 3 of 3 finished successfully.
        ☆  Median run  ☆

                        │
            Speed Index │████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ 3,593
                        │
    Time to Interactive │██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 3,636
                        │
         First CPU Idle │████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ 3,512
                        │
 First Meaningful Paint │████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ 3,512
                        │
 First Contentful Paint │████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ 3,512
                        ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                         0                                                                 Time (ms) since navigation start                                                                 4,000

  ✘ Error: First Contentful Paint. Expected 6 ms, but found 3512 ms.
  ✘ Error: First Meaningful Paint. Expected 1 ms, but found 3512 ms.
  ✘ Error: First CPU Idle. Expected 10 ms, but found 3512 ms.
  ✘ Error: Time to Interactive. Expected 12 ms, but found 3636 ms.
  ✘ Error: Speed Index. Expected 6 ms, but found 3593 ms.
Expectation with errors.
✨  Done in 15.40s.
```

It says that there is some errors, but the exit code `0`, not `1`.

### Environment
1. `pwmetrics` version: 4.0.1
2. Chrome version: Google Chrome 71.0.3559.6 dev
3. OS version: Debian GNU/Linux 8 and Mac OSX

### PR DESCRIPTION
**Pull request by GuillaumeAmat**
Fix #193 

A bit of refact of the `start` method, in order to return 1 as the exit code when expectations have errors.

### CODE REVIEW

**Comment by GuillaumeAmat** [comment]
@denar90 My PR is working well as you can see. The Travis job is failing due to the set expectations ^^

Can I raise them a bit?

**Comment by denar90** [comment]
Hi @GuillaumeAmat. The reason we don't fail when expectations haven't met because users might run several pages in one process. If the first page fails, the process will exit and other pages will be skipped. 
You will be able to handle this stuff manually in your code when https://github.com/paulirish/pwmetrics/issues/188 will be done.

**Comment by GuillaumeAmat** [comment]
Oh, I understand. But as #188 helps to fill the gap, it not makes it easier to achieve :/

In my use case, all my pages are tested concurrently in parallel CI jobs. It is more efficient IMHO. But anyway, an easy way to fail the CI would be much appreciated.

What about a new option? Eg: `--fail-on-error`

**Comment by denar90** [comment]
Oh, I see. `--fail-on-error` will be nice to have. Good idea!

**Comment by GuillaumeAmat** [comment]
Done :)

**Comment by GuillaumeAmat** [comment]
@denar90 Do you know when you (or someone else) will be able to merge it (if it is ok) and release it?

**Comment by denar90** [comment]
I'll look at it later today)

File: lib/index.ts [hunk 1]
```diff
@@ -67,7 +74,7 @@ class PWMetrics {
     this.logger = Logger.getInstance({showOutput: this.flags.showOutput});
   }
 
-  async start() {
+  async start(outputDataCallback) {
```
Comment (denar90) [inline lib/index.ts]: I'm ok with cb for now. wdyt if in future we make `outputDataCallback` like method of PWMetrics class and drop code from cli.js. It can be more clear to read and logic for handling flags will be placed in one class?

**Comment by denar90** [comment]
Published 💥

File: lib/index.ts (hunk 1 above)
Comment (GuillaumeAmat) [reply lib/index.ts]: Sure! I didn't put that code in the class because I thought it was there, in the promise chain, on purpose. I'll do that.

**Comment by GuillaumeAmat** [comment]
Thanks! 🤗

File: lib/index.ts (hunk 1 above)
Comment (GuillaumeAmat) [reply lib/index.ts]: Done in https://github.com/paulirish/pwmetrics/pull/195

**Comment by sejoker** [comment]
exactly what I needed, thanks for landing this.

**Comment by GuillaumeAmat** [comment]
You're welcome @sejoker ;)
